md error404  
echo.> error404\index.js
md aboutUs  
echo.> aboutUs\index.js
md awards  
echo.> awards\index.js
md blogDetails  
echo.> blogDetails\index.js
md blogStandard  
echo.> blogStandard\index.js
md career  
echo.> career\index.js
md caseDetails  
echo.> caseDetails\index.js
md caseStudy01  
echo.> caseStudy01\index.js
md caseStudy02  
echo.> caseStudy02\index.js
md contact  
echo.> contact\index.js
md faqs  
echo.> faqs\index.js
md home2  
echo.> home2\index.js
md home3  
echo.> home3\index.js
md home4  
echo.> home4\index.js
md index  
echo.> index\index.js
md missionVision  
echo.> missionVision\index.js
md ourService  
echo.> ourService\index.js
md ourService02  
echo.> ourService02\index.js
md pricingTable  
echo.> pricingTable\index.js
md serviceDetails  
echo.> serviceDetails\index.js
md teamDetails  
echo.> teamDetails\index.js
md teamMember  
echo.> teamMember\index.js
